# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: master

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x]
    defaults:
      run:
        working-directory: ./backend_stock_service
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v1.2.0
      with:
        key: bmodules
        path: ./backend_stock_service/node_modules
    - run: npm install
    - run: npm run build --if-present


  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x]
    defaults:
      run:
        working-directory: ./image-app
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache
      uses: actions/cache@v1.2.0
      with:
        key: fmodules
        path: ./image-app/node_modules
    - run: npm install
    - run: npm run build --if-present

